#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Constants Module for Lithophane Lamp Generator
Centralized definitions for magic numbers and configuration values.
"""

import math

# ===== Image Processing Constants =====

# Edge detection thresholds
CANNY_THRESHOLD_LOW = 50
CANNY_THRESHOLD_HIGH = 150

# Face detection CLAHE parameters
FACE_CLAHE_CLIP_LIMIT = 1.2
FACE_CLAHE_TILE_SIZE = (6, 6)
FACE_ORIGINAL_BLEND_WEIGHT = 0.7
FACE_ENHANCED_BLEND_WEIGHT = 0.3

# General CLAHE parameters
GENERAL_CLAHE_CLIP_LIMIT = 1.5
GENERAL_CLAHE_TILE_SIZE = (8, 8)

# Portrait enhancement parameters
PORTRAIT_FINE_DETAIL_WEIGHT = 0.05
PORTRAIT_STRUCTURE_DETAIL_WEIGHT = 0.03
PORTRAIT_CLAHE_CLIP_LIMIT = 1.5
PORTRAIT_CLAHE_TILE_SIZE = (8, 8)

# Gaussian blur parameters
GAUSSIAN_FINE_SIGMA = 0.8
GAUSSIAN_COARSE_SIGMA = 2.0

# Bilateral filter parameters
BILATERAL_D_FIRST = 5
BILATERAL_SIGMA_COLOR_FIRST = 30
BILATERAL_SIGMA_SPACE_FIRST = 30
BILATERAL_D_SECOND = 7
BILATERAL_SIGMA_COLOR_SECOND = 40
BILATERAL_SIGMA_SPACE_SECOND = 40

# Lithophane smoothing parameters - Portrait
LITHO_PORTRAIT_BILATERAL_D_1 = 15
LITHO_PORTRAIT_BILATERAL_SIGMA_COLOR_1 = 100
LITHO_PORTRAIT_BILATERAL_SIGMA_SPACE_1 = 100
LITHO_PORTRAIT_BILATERAL_D_2 = 15
LITHO_PORTRAIT_BILATERAL_SIGMA_COLOR_2 = 100
LITHO_PORTRAIT_BILATERAL_SIGMA_SPACE_2 = 100
LITHO_PORTRAIT_BILATERAL_D_3 = 11
LITHO_PORTRAIT_BILATERAL_SIGMA_COLOR_3 = 90
LITHO_PORTRAIT_BILATERAL_SIGMA_SPACE_3 = 90
LITHO_PORTRAIT_GAUSSIAN_KERNEL = (9, 9)
LITHO_PORTRAIT_GAUSSIAN_SIGMA = 3.0
LITHO_PORTRAIT_BLEND_SMOOTH = 0.85
LITHO_PORTRAIT_BLEND_ORIGINAL = 0.15

# Lithophane smoothing parameters - Non-portrait
LITHO_GENERAL_BILATERAL_D_1 = 11
LITHO_GENERAL_BILATERAL_SIGMA_COLOR_1 = 80
LITHO_GENERAL_BILATERAL_SIGMA_SPACE_1 = 80
LITHO_GENERAL_BILATERAL_D_2 = 9
LITHO_GENERAL_BILATERAL_SIGMA_COLOR_2 = 70
LITHO_GENERAL_BILATERAL_SIGMA_SPACE_2 = 70
LITHO_GENERAL_GAUSSIAN_KERNEL = (7, 7)
LITHO_GENERAL_GAUSSIAN_SIGMA = 2.0
LITHO_GENERAL_BLEND_SMOOTH = 0.8
LITHO_GENERAL_BLEND_ORIGINAL = 0.2

# Professional sharpening parameters (REDUCED for smooth lithophanes)
SHARPENING_DETAIL_WEIGHT = 0.10  # Reduced from 0.25 - much less detail enhancement
SHARPENING_STRUCTURE_WEIGHT = 0.05  # Reduced from 0.15 - less structure sharpening
SHARPENING_ORIGINAL_WEIGHT = 0.85
SHARPENING_ENHANCED_WEIGHT = 0.15

# Image classification thresholds
CONTRAST_LOW_THRESHOLD = 25
BRIGHTNESS_UNDEREXPOSED_THRESHOLD = 70
BRIGHTNESS_OVEREXPOSED_THRESHOLD = 185
SHADOW_HEAVY_RATIO_THRESHOLD = 0.4
HIGHLIGHT_HEAVY_RATIO_THRESHOLD = 0.3

# Exposure correction parameters
UNDEREXPOSURE_GAMMA = 0.7
UNDEREXPOSURE_SHADOW_THRESHOLD = 0.3
UNDEREXPOSURE_SHADOW_BOOST = 0.1

OVEREXPOSURE_GAMMA = 1.3
OVEREXPOSURE_HIGHLIGHT_THRESHOLD = 0.8
OVEREXPOSURE_HIGHLIGHT_COMPRESS = 0.4

# Shadow and highlight processing
SHADOW_LIFT_THRESHOLD = 0.4
SHADOW_LIFT_GAMMA = 0.6
HIGHLIGHT_COMPRESS_THRESHOLD = 0.7
HIGHLIGHT_COMPRESS_FACTOR = 0.6

# Contrast enhancement
CONTRAST_ENHANCE_CLAHE_CLIP = 2.5
CONTRAST_ENHANCE_CLAHE_TILE_SIZE = (8, 8)

# Problematic area detection thresholds
DARK_ACCESSORIES_THRESHOLD = 20
DARK_ACCESSORIES_MIN_AREA = 500
DARK_ACCESSORIES_AREA_RATIO = 0.02

BRIGHT_SPOTS_THRESHOLD = 245
BRIGHT_SPOTS_MIN_AREA = 300
BRIGHT_SPOTS_AREA_RATIO = 0.05

TEXT_DETECTION_MIN_AREA = 200
TEXT_DETECTION_AREA_RATIO = 0.02

# Problematic area fixing parameters
DARK_FIX_THRESHOLD = 25
DARK_FIX_SURROUNDING_THRESHOLD = 50
DARK_FIX_ORIGINAL_WEIGHT = 0.8
DARK_FIX_REPLACEMENT_WEIGHT = 0.2

BRIGHT_FIX_THRESHOLD = 240
BRIGHT_FIX_COMPRESS_FACTOR = 0.6

TEXT_REMOVAL_ORIGINAL_WEIGHT = 0.7
TEXT_REMOVAL_INPAINT_WEIGHT = 0.3
TEXT_REMOVAL_INPAINT_RADIUS = 2

# Multi-stage resize thresholds
RESIZE_VERY_LARGE_FACTOR = 3.0
RESIZE_MEDIUM_FACTOR = 1.5
RESIZE_INTERMEDIATE_SCALE = 1.8
RESIZE_STAGE1_SCALE_FACTOR = 2.5
RESIZE_STAGE2_SCALE_FACTOR = 1.5
RESIZE_STAGE3_SCALE_FACTOR = 1.8

# Post-resize sharpening
RESIZE_SHARPEN_KERNEL_CENTER = 1.8
RESIZE_SHARPEN_KERNEL_EDGE = -0.1
RESIZE_SHARPEN_ORIGINAL_WEIGHT = 0.85
RESIZE_SHARPEN_ENHANCED_WEIGHT = 0.15

# ===== 3D Mesh Generation Constants =====

# Curvature compensation
CURVATURE_COMPENSATION_FACTOR = 0.03
CURVATURE_ANGLE_SCALE = 0.8

# Edge blending
EDGE_BLEND_PADDING_MIN = 6
EDGE_BLEND_KERNEL_DIVISOR = 2
EDGE_BLEND_GAUSSIAN_SIGMA_DIVISOR = 2.5

# Mesh validation thresholds
MESH_MIN_VERTEX_COUNT = 100
MESH_MAX_VERTEX_COUNT = 500000

# ===== Material Constants =====

# PLA material properties
PLA_DENSITY_G_CM3 = 1.24  # grams per cubic centimeter

# Printing estimates
PRINT_TIME_FACTOR_HOURS_PER_CM3 = 0.5  # Approximate print time
PRINT_TIME_MINIMUM_HOURS = 2.0  # Minimum estimated print time

# ===== File Processing Constants =====

# Memory management
MEMORY_WARNING_THRESHOLD_GB = 1.0

# File size limits
DEFAULT_MAX_IMAGE_SIZE_MB = 50

# ===== Histogram Analysis Constants =====

HISTOGRAM_BINS = 256
HISTOGRAM_RANGE = [0, 256]
HISTOGRAM_SHADOW_CUTOFF = 64
HISTOGRAM_HIGHLIGHT_CUTOFF = 192

# Histogram normalization parameters
HISTOGRAM_NORMALIZATION_MIN_RANGE = 150  # Minimum tonal range before normalization
HISTOGRAM_NORMALIZATION_PERCENTILE_LOW = 0.02  # 2nd percentile
HISTOGRAM_NORMALIZATION_PERCENTILE_HIGH = 0.98  # 98th percentile
HISTOGRAM_NORMALIZATION_TARGET_MIN = 10  # Target minimum value after normalization
HISTOGRAM_NORMALIZATION_TARGET_MAX = 245  # Target maximum value after normalization
HISTOGRAM_NORMALIZATION_BLEND_NORMALIZED = 0.7  # Weight for normalized image
HISTOGRAM_NORMALIZATION_BLEND_ORIGINAL = 0.3  # Weight for original image

# ===== Morphological Operations Constants =====

MORPH_KERNEL_DARK_SIZE = (10, 10)
MORPH_KERNEL_BRIGHT_SIZE = (8, 8)
MORPH_KERNEL_TEXT_HORIZONTAL = (20, 1)
MORPH_KERNEL_TEXT_VERTICAL = (1, 20)

# ===== Quality Thresholds =====

# Image quality scoring
QUALITY_SCORE_EXCELLENT_MIN = 90
QUALITY_SCORE_GOOD_MIN = 75
QUALITY_SCORE_ACCEPTABLE_MIN = 60

# Resolution thresholds (in pixels)
RESOLUTION_HIGH_MIN = 2000
RESOLUTION_MEDIUM_MIN = 1000
RESOLUTION_LOW_MAX = 800

# ===== Default Settings =====

# Default cylinder dimensions (mm)
DEFAULT_CYLINDER_DIAMETER = 60.0
DEFAULT_CYLINDER_HEIGHT = 130.0
DEFAULT_WALL_THICKNESS = 2.0

# Default lithophane parameters
DEFAULT_MIN_THICKNESS = 0.5
DEFAULT_MAX_THICKNESS = 2.2
DEFAULT_RESOLUTION = 0.08
DEFAULT_LITHOPHANE_COVERAGE_ANGLE = 190.0

# Default margins
DEFAULT_BOTTOM_MARGIN = 2.0
DEFAULT_TOP_MARGIN = 2.0
DEFAULT_EDGE_BLEND_WIDTH = 4.0

# Default printing parameters
DEFAULT_LAYER_HEIGHT = 0.12
DEFAULT_NOZZLE_DIAMETER = 0.4

# Default performance settings
DEFAULT_OPENCV_THREADS = 4

# ===== Logging Constants =====

LOG_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
LOG_DATE_FORMAT = '%Y-%m-%d %H:%M:%S'

# ===== UI Constants =====

# Progress stages
PROGRESS_VALIDATION = (0, 15)
PROGRESS_IMAGE_PROCESSING = (15, 35)
PROGRESS_MESH_GENERATION = (35, 85)
PROGRESS_EXPORT = (85, 100)

# Status update intervals
STATUS_UPDATE_INTERVAL_MS = 100

# ===== Mathematical Constants =====

TWO_PI = 2 * math.pi
HALF_PI = math.pi / 2

# ===== Cylindrical Blending Constants =====

# Minimum blend pixels for edge blending
CYLINDRICAL_BLEND_MIN_PIXELS = 2

# ===== Mesh Resolution Constants =====

# Angular segments (circumference resolution)
MESH_ANGULAR_SEGMENTS_MIN = 800
MESH_ANGULAR_SEGMENTS_MAX = 1400

# Height segments (vertical resolution)
MESH_HEIGHT_SEGMENTS_MIN = 600
MESH_HEIGHT_SEGMENTS_MAX = 1200

# Resolution calculation multiplier
MESH_RESOLUTION_MULTIPLIER = 0.7

# ===== Filename Display Constants =====

# Maximum filename length for GUI display
MAX_FILENAME_DISPLAY_LENGTH = 50
MIN_PRINTABLE_CHAR_CODE = 32

# ===== Worker Thread Constants =====

# Graceful shutdown timeout (milliseconds)
WORKER_SHUTDOWN_TIMEOUT_MS = 3000
